- apps/website/components/templates/landing/landing.tsx
- apps/website/components/templates/landing/title.tsx
- apps/website/pages/_app.tsx
- apps/website/pages/index.tsx
- libs/theme/src/ui/theme-provider/global-styles.tsx
- libs/theme/src/ui/theme-provider/theme-provider.tsx
- libs/ui/src/hooks/use-breakpoint.ts
> feat: page-specific next container full height

- apps/website/i18n.json
- apps/website/locales/en/dashboard-new-user.json
- apps/website/pages/new-user.tsx
- [] - feature
- [] - bugfix
- [] - chore
- [] - docs
Lorem Ipsum
> feat: started profile sign-up

- apps/website/components/molecules/credential-card.tsx
- apps/website/components/organisms/poc-modal-created/poc-modal-created.tsx
- apps/website/components/templates/landing/landing.tsx
- package.json
- yarn.lock
[Credential PoC] - PoC modal
- [] - feature
https://app.asana.com/0/1202049003343323/1202265788256680/f
https://www.figma.com/file/JfeJfC41VkySeGEtCd8ane/Credential?node-id=911%3A26361
> [Credential PoC] - PoC modal

- apps/website/components/organisms/navbar/navbar-menu.tsx
- apps/website/components/organisms/navbar/navbar.tsx
- apps/website/components/templates/dashboard/dashboard.tsx
- apps/website/components/templates/dashboard/drawer/daos-list.tsx
- apps/website/components/templates/dashboard/drawer/drawer-container.tsx
- apps/website/components/templates/dashboard/drawer/drawer.tsx
- apps/website/components/templates/dashboard/drawer/index.ts
- apps/website/components/templates/dashboard/drawer/responsive-drawer.tsx
- apps/website/components/templates/dashboard/drawer/temporary-dao.tsx
- apps/website/components/templates/dashboard/types.ts
- apps/website/hooks/use-nav.tsx
- apps/website/pages/_app.tsx
Show sidebar on mobile
https://user-images.githubusercontent.com/3723280/172497979-1e3c5a32-ff3c-431d-a71e-6b61f5dcd9f0.mp4
> feat: hide and show navigation drawer

- apps/website/components/molecules/add-task/add-task-card.tsx
- apps/website/components/molecules/add-task/hold-token-task/__mock__.ts
- apps/website/components/molecules/add-task/hold-token-task/hold-token-task.tsx
- apps/website/components/templates/create-gate/schema.ts
> Feature: Hold Token Task

- apps/website/components/molecules/add-task/add-task-card.tsx
- apps/website/components/molecules/add-task/hold-token-task/__mock__.ts
- apps/website/components/molecules/add-task/hold-token-task/hold-token-task.tsx
- apps/website/components/molecules/add-task/snapshot-task/snapshot-task.tsx
- apps/website/components/molecules/creators-input.tsx
- apps/website/components/organisms/tasks-area/tasks-area.tsx
- apps/website/components/templates/create-gate/schema.ts
> Feature: Snapshot Task

- apps/website/components/templates/dao-profile/dao-header.tsx
- apps/website/components/templates/profile/PrivateProfileTemplate.tsx
- [] - feature
- [] - chore
- [] - docs
Added 24px padding-top on displayname on user profile and dao profile : https://airtable.com/app1gapmC62c8UJsn/tblwmxXDTHo5Jnlpp/viw3iLMDCLXwNUKYb/rec53AjRHhCFoN8Gs?blocks=hide
> fix : padding top on dao profile , user profile template

- apps/website/locales/en/index.json
- [] - feature
- [] - bugfix
- [] - chore
changes the texts of the elements as mentioned in the airtable
https://airtable.com/app1gapmC62c8UJsn/tblwmxXDTHo5Jnlpp/viw3iLMDCLXwNUKYb/recn0AwhlRej13FOo?blocks=hide
> fix : changes texts

- apps/website/components/molecules/gates-card.tsx
- [] - feature
- [] - chore
- [] - docs
Changed the clickable area to the entire gate card. earlier It was  only on the image section
> fix : Changed the clickable area to entire gate card

- apps/website/components/templates/explore/tabs/daos-tab/table-view.tsx
- apps/website/components/templates/explore/tabs/gates-tab/table-view.tsx
- apps/website/components/templates/explore/tabs/people-tab/table-view.tsx
[Airtable Link](https://airtable.com/app1gapmC62c8UJsn/tblwmxXDTHo5Jnlpp/viwZz80FNpJNyWeTE/recxGVfemXuupSHrU?blocks=hide)
- [✅ ] - bugfix
The items from list viewing is not clickable on gates/daos/people
> Fix: List viewing is not clickable

- apps/website/components/templates/landing/schedule-demo/schedule-demo.tsx
https://airtable.com/app1gapmC62c8UJsn/tblwmxXDTHo5Jnlpp/viwZz80FNpJNyWeTE/rec2aBnBqY8giPpbC?blocks=hide
> Schedule a Demo

- apps/website/components/molecules/form/avatar-background-fields/avatar-background-fields.tsx
changed cursor option into a pointer as mentioned in airtable for edit profile page on cover and avatar section
[AIRTABLE LINK](https://airtable.com/app1gapmC62c8UJsn/tblwmxXDTHo5Jnlpp/viw7qt8Z4mrljQiHq/rec4LtOG7P81rO1Mo?blocks=hide)
> styles: change cursor option on edit profile and cover section

- apps/website/components/organisms/navbar/client-nav.tsx
https://airtable.com/app1gapmC62c8UJsn/tblwmxXDTHo5Jnlpp/viw3iLMDCLXwNUKYb/recfJzPOOYQ2Rxvc4?blocks=hide
> chore: commented out navabar notification component

- apps/website/components/molecules/radio-checkbox-creator/option-field/option-field.tsx
- apps/website/components/molecules/radio-checkbox-creator/radio-checkbox-creator.tsx
- apps/website/components/organisms/gates/view/tasks/content/self-verify.tsx
- apps/website/components/organisms/navbar/navbar.tsx
- apps/website/components/organisms/tasks-area/tasks-area.tsx
- apps/website/components/templates/create-gate/schema.ts
- apps/website/components/templates/gate-view/gate-view.tsx
- apps/website/pages/gate/[id].tsx
Fixed text breack and flex wrap.
> fixed issues on gate viewing and gate creation

- apps/website/components/molecules/dao-card.tsx
- apps/website/components/templates/search/search.tsx
- apps/website/components/templates/search/tabs/daos-tab/daos-tab.tsx
- apps/website/services/queries/home.gql
Added number of followers and gates at dao card.
> added followers and gates numbers in dao card

- apps/website/components/molecules/dao-card.tsx
- apps/website/components/molecules/gates-card.tsx
- [] - bugfix
Removed bookmark button from gates-card
> removed bookmark button from gates card

- apps/website/components/templates/dao-profile/socials.tsx
- apps/website/components/templates/gate-view/gate-view.tsx
Added Share button to Gate view
> added share button on gateway view

- apps/website/components/molecules/ categories-list.tsx
- apps/website/components/molecules/gates-card.tsx
- [] - feature
Added popover when categories in gates are larger than should be.
> Added categories popover and removed unused deps

- apps/website/components/templates/gate-view/gate-view.tsx
Added links to Dao, Holders and Create_by
> Added links to respectives profiles

- apps/website/components/templates/create-gate/create-gate.tsx
https://airtable.com/app1gapmC62c8UJsn/tblwmxXDTHo5Jnlpp/viwd77dIfNTvzi7yw/recEZtQJ3nAWalUzT?blocks=hide
> fix : Layout alignment between details and tasks

- apps/website/components/templates/landing/footer/footer.tsx
- apps/website/components/templates/landing/footer/types.tsx
- apps/website/locales/en/index.json
- apps/website/services/mutations/subscribe-to-newsletter.gql
Added newsletter subscription to Landing page
> added newsletter subscription

- apps/website/components/molecules/sections/section-with-slider-responsive.tsx
[Airtable link](https://airtable.com/app1gapmC62c8UJsn/tblwmxXDTHo5Jnlpp/viwZ6SkouLMBzbEWD/rec342BifGZYW6PWK?blocks=hide)
> fix(explore): update mediaquery breakpoint on explore page

- apps/website/pages/_app.tsx
[Airtable link](https://airtable.com/app1gapmC62c8UJsn/tblwmxXDTHo5Jnlpp/viwZ6SkouLMBzbEWD/recJAkT4tKfbA8qJc?blocks=hide)
> fix(global): change linear progress bar from next to materialui

- apps/website/components/molecules/categories-list.tsx
- apps/website/components/molecules/gates-card.tsx
- apps/website/components/templates/dao-profile/dao-header.tsx
- apps/website/constants/dao.ts
- libs/theme/src/ui/theme-provider/global-styles.tsx
[Gate Card](https://airtable.com/app1gapmC62c8UJsn/tblwmxXDTHo5Jnlpp/viwZ6SkouLMBzbEWD/recX9uwpzZ4u69UtT?blocks=hide)
[DAO Card](https://airtable.com/app1gapmC62c8UJsn/tblwmxXDTHo5Jnlpp/viwZ6SkouLMBzbEWD/recmztxJVNQmOW15t?blocks=hide)
[Removing input background colour for Chrome autocomplete](https://airtable.com/app1gapmC62c8UJsn/tblwmxXDTHo5Jnlpp/viwZ6SkouLMBzbEWD/recTxoFWVj3FczEaw?blocks=hide)
> Fixes: Bookmarking, DAO Categories, Inputs background

- .dockerignore
- Dockerfile
- apps/website/next.config.js
- package.json
- yarn.lock
Created Dockerfile for Next.js to upload on AWS
> Dockering Next.js

- apps/website/components/molecules/dao-card.tsx
- apps/website/components/templates/profile/tabs/OverviewTab.tsx
- Hide Edit option on the Experience section on profile page 
- Changed Contributors to Followers 
Lorem Ipsum
> Quick UI changes - asked by Ayyan and Sanket

- apps/website/components/templates/dao-profile/dao-profile.tsx
- apps/website/components/templates/explore/explore.tsx
- apps/website/components/templates/profile/PrivateProfileTemplate.tsx
- apps/website/components/templates/profile/ProfileTemplate.tsx
- apps/website/components/templates/search/search.tsx
> fixed padding and some minor styling mentioned by tulio

- apps/website/components/templates/create-gate/create-gate.tsx
- apps/website/components/templates/create-gate/gate-image-card/gate-data.tsx
- Fixed Responsiveness 
- Make title and description for two lines
- 
Lorem Ipsum
> Fix Responsiveness on Create Gate Page and other Tweaks

- apps/website/components/atoms/read-more-less.tsx
- apps/website/components/templates/gate-view/gate-view.tsx
[FIGMA LINK](https://www.figma.com/file/tanF8XYlxGi6eb8dEhXNf4/Gate-Viewing?node-id=4%3A21413)
> feat : added see more and see less paragraph  global feature

- apps/website/components/organisms/tasks/task.tsx
- apps/website/components/templates/credential/credential.tsx
[AIRTABLE LINK](https://airtable.com/app1gapmC62c8UJsn/tblwmxXDTHo5Jnlpp/viwHuUYiJVjgEZGWY/recsZfGOQNhyz75zj?blocks=hide)
> styles : fix padding responsiveness issue

- apps/website/components/templates/explore/tabs/all-tab/all-tab.tsx
[AIRTABLE LINK](https://airtable.com/app1gapmC62c8UJsn/tblwmxXDTHo5Jnlpp/viwd77dIfNTvzi7yw/rec0czWmWwivt8CPg?blocks=hide)
> style : fix reponsiveness issue for dao card

- apps/website/components/templates/credential/credential.tsx
[AIRTABLE LINK](https://airtable.com/app1gapmC62c8UJsn/tblwmxXDTHo5Jnlpp/viwd77dIfNTvzi7yw/recCVzpVhfNorqXjC?blocks=hide)
> feat : added navbar

- apps/website/components/molecules/add-task/hold-token-task/hold-token-task.tsx
- apps/website/components/molecules/add-task/snapshot-task/snapshot-task.tsx
- apps/website/components/molecules/add-task/verification-task/verification-task.tsx
- apps/website/components/templates/create-gate/create-gate.tsx
Bugs 
Padding issue - Nav bar
Label and Description overlapping 
> Create Page Ui Tweaks

- apps/website/components/templates/profile/PrivateProfileTemplate.tsx
- apps/website/components/templates/profile/edit/Components/guide-card/index.tsx
I added the logic for the guide card on the private profile view.
> feat: connected guide card to backend information

- apps/website/components/atoms/share-button.tsx
- apps/website/locales/en/common.json
- apps/website/utils/map-object.ts
Share menu on DAO Profile and Gate View
> feat: share button to share menu

- apps/website/providers/biconomy/biconomy-provider.tsx
- package.json
- yarn.lock
Quick hotfix for production: removed calls to Rinkeby
> hotfix: biconomy problem

- apps/website/components/templates/explore/tabs/people-tab/people-tab.tsx
- apps/website/services/queries/home.gql
- apps/website/services/query-client.ts
- added load more button
- only "me" and "token" can be cached on localstorage
> Load more button on explore page

- apps/website/pages/_app.tsx
[ASANA LINK](https://app.asana.com/0/1202770668722101/1202901048522797/f)
> fix:loading bar

- apps/website/components/templates/profile/PrivateProfileTemplate.tsx
- apps/website/pages/earned/[id].tsx
- apps/website/pages/profile/[username].tsx
- [] - feature
- [] - bugfix
- [] - chore
- [] - docs
Lorem Ipsum
> fix: ssr on earned and profile

- apps/website/components/organisms/gates/view/tasks/content/self-verify.tsx
- apps/website/components/organisms/gates/view/tasks/content/snapshot.tsx
[ASANA LINK](https://app.asana.com/0/1202770668722101/1202962589476942/f)
> fix : responsiveness for self verify and snapshot

- apps/website/components/templates/explore/explore.tsx
[ASANA LINK](https://app.asana.com/0/1202770668722101/1202223082829511/f)
> fix: tab scrolling for mobile

- apps/website/components/molecules/add-task/add-task-card.tsx
- apps/website/components/molecules/add-task/file-link-task/file-link-task.tsx
- apps/website/components/molecules/add-task/hold-token-task/hold-token-task.tsx
- apps/website/components/molecules/add-task/quiz-task/quiz-task.tsx
- apps/website/components/molecules/add-task/snapshot-task/snapshot-task.tsx
- apps/website/components/molecules/add-task/verification-task/verification-task.tsx
- apps/website/components/organisms/navbar/navbar-notifications/navbar-notifications.tsx
- apps/website/components/organisms/tasks/task.tsx
- apps/website/components/templates/create-gate/create-gate.tsx
- apps/website/components/templates/explore/tabs/gates-tab/table-view.tsx
- apps/website/components/templates/explore/tabs/people-tab/people-tab.tsx
- apps/website/components/templates/gate-view/gate-view.tsx
- apps/website/components/templates/profile/tabs/OverviewTab.tsx
- apps/website/components/templates/profile/tabs/experience/experience-accordion.tsx
- apps/website/components/templates/search/search.tsx
- [ASANA LINK](https://app.asana.com/0/1202770668722101/1202983370735479/f)
- [ASANA LINK](https://app.asana.com/0/1202770668722101/1202983372084001/f)
- [ASANA LINK](https://app.asana.com/0/1202770668722101/1202983371279341/f)
> UI bug fixes

- apps/website/components/organisms/tasks/task.tsx
- apps/website/components/templates/gate-view/gate-view.tsx
- apps/website/services/queries/gate.gql
- [ASANA LINK](https://app.asana.com/0/1202770668722101/1202983370735490/f)
> feat : add label bar for gate completation

- apps/website/components/organisms/tasks/task.tsx
- apps/website/components/templates/gate-view/gate-view.tsx
> hotfix: fix bug on completedAt

- apps/website/components/molecules/add-task/snapshot-task/snapshot-task.tsx
- apps/website/components/templates/gate-view/gate-view.tsx
- [ASANA LINK](https://app.asana.com/0/1202770668722101/1203004494148304/f)
> feat : changed checked component into radio one

- apps/website/services/web3/client.ts
remove autoconnect when the user lands on the website
> fix: remove auto walet connection

- apps/website/components/atoms/follow-button-dao.tsx
- apps/website/components/molecules/dao-card.tsx
- apps/website/components/organisms/tasks/task-error-messages.ts
- apps/website/components/organisms/tasks/task.tsx
- apps/website/components/templates/create-gate/schema.ts
- apps/website/components/templates/profile/tabs/OverviewTab.tsx
- apps/website/hooks/use-follow.ts
- apps/website/hooks/use-protected.ts
- apps/website/locales/en/search.json
- apps/website/pages/_app.tsx
- apps/website/providers/biconomy/biconomy-provider.tsx
- apps/website/services/web3/client.ts
- package.json
- yarn.lock
- [] - feature
- [] - bugfix
- [] - chore
- [] - docs
Lorem Ipsum
> Release - Prod (28/set) [staging]

- apps/website/providers/biconomy/biconomy-provider.tsx
Fixed problem of minting on different wallets/providers.
> fix: allowed minting on different wallets

- apps/website/providers/biconomy/biconomy-provider.tsx
> fix: walletconnect

- apps/website/components/templates/gate-view/gate-view.tsx
- apps/website/services/queries/gate.gql
> feat: implemented computer field holder_count; fixed http 413

- apps/website/components/molecules/image-drop-field/edit-dropdown-menu.tsx
- apps/website/components/molecules/image-drop-field/image-drop-field.tsx
- apps/website/components/molecules/image-drop-field/placeholder.tsx
- apps/website/components/templates/create-gate/create-gate.tsx
- apps/website/components/templates/create-gate/gate-image-card/gate-data.tsx
- apps/website/components/templates/create-gate/gate-image-card/gate-image-card.tsx
- apps/website/locales/en/common.json
- [ASANA LINK](https://app.asana.com/0/1202770668722101/1202983370735500/f)
> Fix drop image field

- apps/website/components/molecules/mint-card/screen/default-mint-screen.tsx
- [] - feature
- [] - bugfix
- [] - chore
- [] - docs
Lorem Ipsum
> Fixed bug on description length into credential card

- apps/website/components/organisms/gates/view/tasks/content/twitter_follow.tsx
- apps/website/components/organisms/gates/view/tasks/content/twitter_retweet.tsx
- apps/website/components/organisms/gates/view/tasks/content/twitter_tweet.tsx
- [] - feature
- [] - bugfix
- [] - chore
- [] - docs
Lorem Ipsum
> fixed twitter UI adjustments

- apps/website/components/templates/explore/tabs/people-tab/people-tab.tsx
- [] - feature
- [] - bugfix
- [] - chore
- [] - docs
Lorem Ipsum
> Fixed ios scrolling

- apps/website/components/organisms/navbar/client-nav.tsx
- apps/website/services/mutations/authentication.gql
- apps/website/services/next-auth.ts
- apps/website/types/user.ts
- loading state for connect button
- remove jwt null error
> fix: pass user id and remove from refresh query

- apps/website/components/templates/gate-view/gate-view.tsx
fix: fixed alignment and removed wrong avatar on holders count
> fix: fixed alignment and removed wrong avatar on holders count

- apps/website/components/organisms/holder-dialog/holder-dialog.tsx
[x] hotfix
- solves loading bar issue while fetching more holder on the dialog
> fix: loading

- apps/website/components/molecules/add-task/add-task-card.tsx
- apps/website/components/molecules/add-task/hold-nft-task/hold-nft-task.tsx
- apps/website/components/organisms/gates/view/tasks/content/nft_hold.tsx
- apps/website/components/organisms/navbar/navbar.spec.tsx
- apps/website/components/organisms/tasks-area/tasks-area.tsx
- apps/website/components/organisms/tasks/task-error-messages.ts
- apps/website/components/organisms/tasks/task.tsx
- apps/website/components/templates/create-gate/schema.ts
Added NFT hold feature, to check if an user holds an NFT from a specific collection on any chain.
> Feature - NFT Task

- apps/website/pages/api/oauth/twitter/post.ts
Added `tweet_mode: 'extended'` to get tweet's full text.
> hotfix: allow extended tweets

- apps/website/components/templates/dashboard/drawer/drawer.tsx
- [] - feature
- [] - bugfix
- [] - chore
- [] - docs
Lorem Ipsum
> Removed framer to trying fix issue

- apps/website/components/organisms/gates/view/tasks/content/quiz.tsx
> feat : added frontend honeypot trap for bots

- apps/website/components/templates/create-gate/create-gate.tsx
- apps/website/components/templates/gate-view/gate-view.tsx
- apps/website/services/mutations/gate.gql
> fix: added new publish gate route

- apps/website/components/atoms/notistack.tsx
- apps/website/components/molecules/add-task/quiz-task/quiz-task.tsx
- apps/website/components/molecules/radio-checkbox-creator/option-field/option-field.tsx
- apps/website/components/templates/create-gate/create-gate.tsx
Fixed problem with saving a credential as a draft
> Hotfix - Quiz

- apps/website/components/organisms/gates/view/tasks/content/twitter_follow.tsx
- apps/website/i18n.js
- apps/website/locales/en/errors.json
- apps/website/pages/api/twitter/get-user-by-username.ts
- package.json
- yarn.lock
Fix Twitter glitch bug; implemented better solutions.
> Hotfix - Twitter Glitch (Prod)

- apps/website/components/organisms/gates/view/tasks/content/twitter_follow.tsx
- apps/website/i18n.js
- apps/website/locales/en/errors.json
- apps/website/pages/api/twitter/get-user-by-username.ts
- package.json
- yarn.lock
Fix Twitter glitch bug; implemented better solutions.
> Hotfix - Twitter Glitch (staging)

- apps/website/components/organisms/gates/view/tasks/content/twitter_follow.tsx
> Hotfix - Twitter Typo

- apps/website/providers/biconomy/biconomy-provider.tsx
- package.json
- yarn.lock
Basically bruteforcing Biconomy (in a healthy way) until it works.
> Hotfix - Biconomy (Staging)

- package.json
- yarn.lock
> Hotfix - Wagmi

- apps/website/components/organisms/gates/view/tasks/content/twitter_follow.tsx
- apps/website/pages/api/oauth/twitter/follow.ts
Temporary solution for Twitter rate limiting/glitching problem.
> Fixed twitter follow issues

- apps/website/components/organisms/tasks/task.tsx
- apps/website/hooks/use-follow.ts
- apps/website/providers/auth/hooks.tsx
- apps/website/providers/biconomy/biconomy-provider.tsx
- apps/website/services/queries/me.gql
> Hotfix - "me" queries (Prod)

- apps/website/components/molecules/add-task/quiz-task/quiz-task.tsx
- apps/website/components/templates/create-gate/create-gate.tsx
- apps/website/components/templates/create-gate/schema.ts
- [] - feature
- [] - bugfix
- [] - chore
- [] - docs
Lorem Ipsum
> Fixed gate create error messages

- apps/website/components/templates/dashboard/drawer/responsive-drawer.tsx
> fix: navbar margin left size

- apps/website/components/atoms/check-button.tsx
- apps/website/components/templates/settings/connected-accounts/components/accounts-card.tsx
- apps/website/locales/en/settings.json
- [] - feature
- [] - bugfix
- [] - chore
- [] - docs
Lorem Ipsum
> Fixed account management issues

- apps/website/components/organisms/tasks/task-error-messages.ts
- apps/website/components/templates/settings/account-management/components/email.tsx
- [] - feature
- [] - bugfix
- [] - chore
- [] - docs
Lorem Ipsum
> Changed error messages

- apps/website/components/molecules/form/social-links/social-link.tsx
- apps/website/components/molecules/form/social-links/social-links.tsx
- apps/website/components/templates/settings/profile/schema.ts
- [] - feature
- [] - bugfix
- [] - chore
- [] - docs
Lorem Ipsum
> Fixed social links issues

- apps/website/components/atoms/follow-button-user/follow-user.tsx
- apps/website/pages/api/notify/index.ts
- apps/website/utils/sqs.ts
- package.json
- yarn.lock
- [] - feature
- [] - bugfix
- [] - chore
- [] - docs
Lorem Ipsum
> add connection to sqs and message emission on following a user

- apps/website/components/templates/settings/account-management/components/email.tsx
- [] - feature
- [] - bugfix
- [] - chore
- [] - docs
Lorem Ipsum
> Improved validations

- apps/website/components/templates/settings/connected-accounts/connectors/github-connection.tsx
- apps/website/pages/oauth/github.tsx
Fix problem with Github environment variables.
> Hotfix - GitHub Envs

- apps/website/providers/biconomy/biconomy-provider.tsx
- package.json
- yarn.lock
Fixed Rainbow and Coinbase Wallet minting issues on Biconomy.
> Hotfix - Rainbow/Coinbase Wallet (Prod)

- apps/website/providers/biconomy/biconomy-provider.tsx
- package.json
- yarn.lock
Fixed Rainbow and Coinbase Wallet minting issues on Biconomy.
> Hotfix - Rainbow/Coinbase Wallet

- apps/website/providers/biconomy/biconomy-provider.tsx
- yarn.lock
> Revert "Hotfix - Rainbow/Coinbase Wallet (Prod)"

- apps/website/providers/biconomy/biconomy-provider.tsx
- yarn.lock
> Revert "Hotfix - Rainbow/Coinbase Wallet"

- apps/website/providers/auth/hooks.tsx
Fix: use correct route as callback
> Hotfix - New User Callback (staging)

- apps/website/providers/auth/hooks.tsx
Fix: use correct route as callback
> Hotfix - New User (Prod)

- apps/website/components/organisms/navbar/navbar-notifications/list.tsx
- apps/website/components/organisms/navbar/navbar-notifications/navbar-notifications.tsx
- apps/website/components/organisms/navbar/navbar-notifications/notifications/custom.tsx
- apps/website/components/templates/dao-profile/dao-profile.tsx
- apps/website/locales/en/gate-new.json
- apps/website/pages/api/notifications/index.ts
- apps/website/pages/api/notify/index.ts
- apps/website/pages/dao/[slug]/index.tsx
- apps/website/utils/sqs.ts
- package.json
- yarn.lock
- [] - feature
- [] - bugfix
- [] - chore
- [] - docs
Lorem Ipsum
> add fetch notifications from redis

- apps/website/components/molecules/image-drop-field/image-drop-field.tsx
> feat: can upload gifs

- apps/website/providers/biconomy/biconomy-provider.tsx
- apps/website/services/mutations/mint.gql
Implemented Biconomy minting on the backend
> feat: implemented Biconomy minting on the backend

- apps/website/components/templates/gate-view/gate-view.tsx
> fix : expiration credential on same day

- apps/website/components/molecules/mint-card/mint-card.tsx
- apps/website/components/molecules/mint-dialog/mint-dialog.tsx
- apps/website/components/templates/gate-view/gate-view.tsx
- apps/website/components/templates/profile/tabs/experience/experience-accordion.tsx
- apps/website/hooks/use-credential.ts
Fixed problem on front-end regarding minting
> hotfix: mint management

- apps/website/locales/en/index.json
Fixed spelling errors on landing page
> chore: fixed spelling errors on landing page

- apps/website/components/atoms/notistack.tsx
- apps/website/components/templates/protocol/components/card-user-cell.tsx
- apps/website/components/templates/protocol/components/copy-paste.tsx
- apps/website/components/templates/protocol/components/floating-cta-button.tsx
- apps/website/components/templates/protocol/components/info-title.tsx
- apps/website/components/templates/protocol/components/tags.tsx
- apps/website/components/templates/protocol/credential/view/components/credential-card-info.tsx
- apps/website/components/templates/protocol/data-model/view/components/data-model-tabs.tsx
- apps/website/components/templates/protocol/data-model/view/components/overview-card-info.tsx
- apps/website/components/templates/protocol/data-model/view/components/overview-tab.tsx
- apps/website/components/templates/protocol/data-model/view/data-model-view.tsx
- apps/website/components/templates/protocol/protocol-template.tsx
- libs/helpers/src/lib/string.ts
- [] - feature
- [] - bugfix
- [] - chore
- [] - docs
Lorem Ipsum
> feat: UI adjustments (QA)

- apps/website/components/templates/protocol/data-models/show/components/data-model-tabs.tsx
- apps/website/components/templates/protocol/index.ts
- apps/website/components/templates/protocol/protocol-template.tsx
- apps/website/hooks/use-window-size.tsx
- [] - feature
- [] - bugfix
- [] - chore
- [] - docs
Lorem Ipsum
> feat: created a playground tab

- apps/website/components/templates/protocol/credentials/create/components/general-info-form.tsx
- apps/website/locales/en/protocol.json
- [] - feature
- [] - bugfix
- [] - chore
- [] - docs
Lorem Ipsum
> fix: added loading and label for issuer field

- apps/website/components/templates/protocol/credentials/create/components/general-info-form.tsx
- apps/website/components/templates/protocol/credentials/create/components/image-field.tsx
- apps/website/components/templates/protocol/credentials/create/components/issue-by-form.tsx
- apps/website/components/templates/protocol/credentials/create/credential-create.tsx
- apps/website/components/templates/protocol/data-models/show/components/data-model-tabs.tsx
- apps/website/locales/en/protocol.json
- [] - feature
- [] - bugfix
- [] - chore
- [] - docs
Lorem Ipsum
> fix: fixed validations problems

- apps/website/components/templates/protocol/credentials/create/components/ClaimTypes.tsx
- apps/website/components/templates/protocol/credentials/create/components/claim-form.tsx
- apps/website/components/templates/protocol/credentials/create/credential-create.tsx
- apps/website/components/templates/protocol/credentials/create/schema.ts
- apps/website/services/gateway-protocol/mutations/credentials.gql
- package.json
- [] - feature
- [] - bugfix
- [] - chore
- [] - docs
Lorem Ipsum
> feat: Added uri field

- apps/website/components/templates/protocol/credentials/show/components/data-table.tsx
- [] - feature
- [] - bugfix
- [] - chore
- [] - docs
Lorem Ipsum
> fix: fixed image preview

- apps/website/components/templates/protocol/credentials/show/components/data-table.tsx
- apps/website/components/templates/protocol/credentials/show/components/link-view.tsx
- [] - feature
- [] - bugfix
- [] - chore
- [] - docs
Lorem Ipsum
> feat: created a link preview for credential page

- apps/website/components/templates/protocol/credentials/create/components/credential-create-container.tsx
- apps/website/components/templates/protocol/credentials/create/credential-create.tsx
- [] - feature
- [] - bugfix
- [] - chore
- [] - docs
Lorem Ipsum
> feat: refactored the credential create page

- apps/website/components/molecules/modal-right.tsx
- apps/website/components/templates/protocol/credentials/create/components/credential-create-container.tsx
- apps/website/components/templates/protocol/credentials/create/credential-create.tsx
- apps/website/components/templates/protocol/data-models/show/data-model-show.tsx
- [] - feature
- [] - bugfix
- [] - chore
- [] - docs
Lorem Ipsum
> fix: Added a global scroll into modal right

- apps/website/components/molecules/modal-right.tsx
- apps/website/components/templates/protocol/components/card-cell.tsx
- apps/website/components/templates/protocol/components/info-title.tsx
- apps/website/components/templates/protocol/credentials/create/components/general-info-form.tsx
- apps/website/components/templates/protocol/credentials/show/components/data-table.tsx
- apps/website/components/templates/protocol/data-models/show/data-model-show.tsx
- apps/website/locales/en/protocol.json
- [] - feature
- [] - bugfix
- [] - chore
- [] - docs
Lorem Ipsum
> Fix/protocol UI fixies

- apps/website/components/atoms/external-link.tsx
- apps/website/components/templates/protocol/credentials/show/components/activities.tsx
- apps/website/components/templates/protocol/credentials/show/credential-show.tsx
- apps/website/components/templates/protocol/data-models/show/components/overview-tab.tsx
- [] - feature
- [] - bugfix
- [] - chore
- [] - docs
Lorem Ipsum
> fix: fixed external link

- apps/website/components/atoms/mint-button.tsx
- apps/website/components/templates/protocol/credentials/show/components/activities.tsx
- apps/website/components/templates/protocol/credentials/show/credential-show.tsx
- apps/website/services/gateway-protocol/queries/credentials.gql
- [] - feature
- [] - bugfix
- [] - chore
- [] - docs
Lorem Ipsum
> fix: Removed activities mock

- apps/website/components/templates/protocol/components/floating-cta.tsx
- [] - feature
- [] - bugfix
- [] - docs
https://app.asana.com/0/1203314700325692/1203874575703422/f
> fix : behaviour of speed dial

- apps/website/components/organisms/data-grid/data-grid.tsx
- apps/website/components/templates/protocol/data-models/show/components/data-model-tabs.tsx
- apps/website/services/gateway-protocol/queries/credentials.gql
- Remove QR Code
- Use gateway ID (username)
> feat: integration username and remove tabs

- apps/website/components/templates/protocol/components/credential-card-info.tsx
- [] - feature
- [] - chore
- [] - docs
Lorem Ipsum
> fix: Removed unused react query

- apps/website/components/templates/protocol/credentials/create/components/successfully-created.tsx
- apps/website/utils/qr-code/qr-code.ts
- [] - bugfix
- [] - chore
- [] - docs
Lorem Ipsum
> feat: added a QR Code to successfully page

- apps/website/components/templates/protocol/credentials/create/components/successfully-created.tsx
- apps/website/components/templates/protocol/credentials/show/components/activities.tsx
- apps/website/components/templates/protocol/credentials/show/components/invalid-status-box.tsx
- apps/website/components/templates/protocol/credentials/show/components/revoke-credential.tsx
- apps/website/components/templates/protocol/credentials/show/credential-show.tsx
- apps/website/locales/en/protocol.json
- apps/website/services/gateway-protocol/mutations/credentials.gql
- [] - bugfix
- [] - chore
- [] - docs
Lorem Ipsum
> feat: added a revoke button

- apps/website/components/templates/protocol/credentials/create/components/claim-form-text.tsx
- [] - feature
- [] - chore
- [] - docs
> fix: disabled scrolling option on age field

- apps/website/components/templates/protocol/credentials/create/components/issue-by-form.tsx
- apps/website/components/templates/protocol/data-models/show/data-model-show.tsx
- apps/website/locales/en/protocol.json
- [] - feature
- [] - bugfix
- [] - chore
- [] - docs
Lorem Ipsum
> feat: added a confirmation dialog before close modal

- apps/website/components/templates/protocol/data-models/show/components/table-schema.tsx
- [] - feature
- [] - bugfix
- [] - chore
- [] - docs
Lorem Ipsum
> fix: fixed chip type to accept link

- apps/website/components/templates/protocol/credentials/create/components/issue-by-form.tsx
- apps/website/components/templates/protocol/credentials/create/credential-create.tsx
- apps/website/components/templates/protocol/credentials/create/schema.ts
- apps/website/services/gateway-protocol/mutations/credentials.gql
- [] - feature
- [] - bugfix
- [] - chore
- [] - docs
Lorem Ipsum
> fix: Removed issuerId and organizationId

- apps/website/components/templates/protocol/credentials/create/credential-create.tsx
- [] - feature
- [] - chore
- [] - docs
Lorem Ipsum
> fix: added conditional to avoid image undefined

- apps/website/components/templates/protocol/credentials/show/credential-show.tsx
You can choose if we will close the dialog after 2.5 seconds or not. You just need to approve this PR, or not.
> feat: close success dialog after 2.5 seconds

- apps/website/components/templates/protocol/credentials/show/components/list-view.tsx
- [] - feature
- [] - chore
- [] - docs
Lorem Ipsum
> fix: Fixed array view

- apps/website/components/organisms/gates/view/tasks/content/twitter_tweet.tsx
Added encodeURI() on the tweet text for the post tweet task.
A baby seal died... :/
> hotfix: encode tweet post

- apps/website/providers/auth/hooks.tsx
- apps/website/services/hasura/mutations/authentication.gql
- [] - feature
- [] - bugfix
- [] - chore
- [] - docs
Lorem Ipsum
> hotfix: fix nonce call

- apps/website/components/templates/protocol/credentials/show/components/mint-nft-card.tsx
- apps/website/components/templates/protocol/credentials/show/credential-show.tsx
- apps/website/services/gateway-protocol/queries/credentials.gql
- [] - bugfix
- [] - chore
- [] - docs
Lorem Ipsum
> feat: added mint solana

- apps/website/components/templates/protocol/credentials/show/components/mint-nft-card.tsx
- apps/website/components/templates/protocol/credentials/show/credential-show.tsx
- [] - feature
- [] - chore
- [] - docs
Lorem Ipsum
> fix: Adjusted mint solana

- apps/website/services/gateway-protocol/api.ts
- [] - feature
- [] - bugfix
- [] - docs
Lorem Ipsum
> feat: add api key to protocol API

- apps/website/pages/_app.tsx
- [] - feature
- 
Adding Google Analytics Snippet
Adding Horjar
> added google analytics  and Hotjar snippet

- apps/website/components/organisms/gates/view/tasks/content/manual/components/comment-card.tsx
- apps/website/components/organisms/gates/view/tasks/content/manual/manual.tsx
- apps/website/components/templates/create-gate/create-gate.tsx
- apps/website/components/templates/create-gate/details-form.tsx
- apps/website/components/templates/create-gate/schema.ts
- apps/website/components/templates/credential/credential.tsx
- apps/website/components/templates/gate-view/gate-view.tsx
- apps/website/services/hasura/mutations/create_gate.gql
- apps/website/services/hasura/queries/credential.gql
- apps/website/services/hasura/queries/gate.gql
- apps/website/services/hasura/queries/search.gql
> chore: removed skills and fix ui for send manual task

- apps/website/components/templates/profile/PrivateProfileTemplate.tsx
- apps/website/components/templates/profile/tabs/Earned.tsx
- apps/website/locales/en/common.json
- [] - bugfix
- [] - chore
- [] - docs
Lorem Ipsum
> feat: added earned tab

- apps/website/components/organisms/tasks/task-error-messages.ts
- apps/website/components/templates/protocol/credentials/create/components/issue-by-form.tsx
- apps/website/components/templates/protocol/credentials/create/credential-create.tsx
- apps/website/components/templates/protocol/data-models/show/components/issue-credential-button.tsx
- apps/website/components/templates/protocol/data-models/show/data-model-show.tsx
- apps/website/locales/en/protocol.json
- apps/website/services/gateway-protocol/queries/dataModels.gql
> Revert "Revert "feat: added restrictions to create a credential""

- apps/website/components/templates/protocol/credentials/create/components/issue-by-form.tsx
- [] - feature
- [] - chore
- [] - docs
Lorem Ipsum
> fix: fixed protocol id

- apps/website/components/templates/profile/PrivateProfileTemplate.tsx
- apps/website/components/templates/profile/ProfileTemplate.tsx
- apps/website/components/templates/profile/tabs/Earned.tsx
- [] - feature
- [] - chore
- [] - docs
Lorem Ipsum
> fïx: fixed public tab earn

- apps/website/pages/_app.tsx
- [] - feature
Adding  dynamic analytics via process.env.NEXT_PUBLIC_ANALYTICS_TAG
Staging = G-MP7XQ5T8QJ
Production = G-CKZ9WYMPM4
> added dynamic tag via environments

- apps/website/components/templates/gate-view/direct-holders-list/direct-holders-list.tsx
- apps/website/components/templates/gate-view/direct-holders-list/header.tsx
- apps/website/components/templates/gate-view/gate-view.tsx
- apps/website/locales/en/credential.json
- libs/assets/src/index.ts
- libs/assets/src/lib/gate-filled.tsx
- [] - feature
- [] - bugfix
- [] - chore
- [] - docs
Lorem Ipsum
> chore : added empty state message for wallets

- apps/website/components/molecules/add-task/quiz-task/quiz-task.tsx
- apps/website/components/organisms/question-creator/question-creator.tsx
- apps/website/components/templates/create-gate/create-gate.tsx
- apps/website/components/templates/create-gate/schema.ts
Fixed this bug: https://app.asana.com/0/1203985419708786/1204236182475417/f
> Hotfix - Question Order

- apps/website/components/organisms/gates/view/tasks/content/quiz.tsx
- apps/website/components/organisms/tasks/task.tsx
Fixed following bug: https://app.asana.com/0/1203985419708786/1204245788065371/f
> Hotfix - Attempt Count

- apps/website/components/templates/gate-view/direct-holders-list/direct-holders-list.tsx
Problem on styling for direct credential list.
> Direct Credential List

- apps/website/components/atoms/share-on.tsx
- apps/website/components/molecules/modal/modal.tsx
> hotfix: credential share dialog size

- apps/website/components/templates/protocol/credentials/show/credential-show.tsx
- apps/website/locales/en/protocol.json
> fix: display share credential after mint

- .graphqlrc.ts
- apps/website/components/templates/settings/account-management/account-management.tsx
- apps/website/components/templates/settings/connected-accounts/connected-accounts.tsx
- apps/website/components/templates/settings/navbar-settings/navbar-settings.tsx
- apps/website/components/templates/settings/notifications/config.ts
- apps/website/components/templates/settings/notifications/notifications.tsx
- apps/website/components/templates/settings/profile/edit-profile.tsx
- apps/website/locales/en/common.json
- apps/website/locales/en/settings.json
- apps/website/services/hasura/mutations/create_user_profile.gql
- apps/website/services/hasura/mutations/settings.gql
- apps/website/services/hasura/queries/me.gql
- apps/website/services/hasura/queries/notifications.gql
- package.json
- yarn.lock
Created Notification Settings page, enabling user which notifications they want to receive via email and on dapp
> Notification Settings

- apps/website/components/atoms/share-on.tsx
- apps/website/components/molecules/head-container.tsx
- apps/website/constants/config.ts
- apps/website/locales/en/common.json
> fix: add environment variable to dev, v2 and production

- apps/website/components/templates/profile/ProfileTemplate.tsx
- apps/website/components/templates/profile/tabs/IssuedTab.tsx
- apps/website/components/templates/profile/tabs/ReceivedTab.tsx
- apps/website/services/gateway-protocol/fragments/credentials.gql
- apps/website/services/gateway-protocol/queries/credentials.gql
- apps/website/services/hasura/fragments/user.gql
Fixed [issue](https://app.asana.com/0/1204321038394512/1204321038394527/f).
> Hotfix - Credentials on public profile

- apps/website/components/templates/new-user/card-summary.tsx
- apps/website/components/templates/new-user/form-verify-token.tsx
- apps/website/components/templates/new-user/new-user.tsx
- apps/website/pages/new-user.tsx
> fix: fixed ui problems.

- apps/website/components/atoms/share-btn-fn.tsx
- apps/website/components/templates/gate-view/gate-view.tsx
##Bug fix 
removed the title and change the creator name to org name
> Twitter fixes

- apps/website/next.config.js
Related to https://github.com/Gateway-DAO/lambda-qrcode-generator/pull/2 PR
> fix: Updated new CDN CloudFront URLs

- apps/website/components/templates/new-user/schema.ts
> fix: adjusted signup schema

- apps/website/components/atoms/alert.tsx
- apps/website/components/templates/loyalty-program/components/Tier.tsx
- apps/website/components/templates/loyalty-program/loyalty-program/components/CredentialListItem.tsx
- apps/website/components/templates/loyalty-program/loyalty-program/components/CredentialsList.tsx
- apps/website/components/templates/loyalty-program/loyalty-program/components/LoyaltyProgramMainContent.tsx
- apps/website/hooks/use-total-points-completed.ts
- apps/website/locales/en/loyalty-program.json
> feat: added alert component and tier information.

- apps/website/components/templates/dao-profile/tabs/overview-tab/overview-tab.tsx
- apps/website/components/templates/dao-profile/tabs/passes-tab.tsx
- apps/website/components/templates/explore/explore.tsx
- apps/website/components/templates/explore/tabs/all-tab/all-tab.tsx
- apps/website/components/templates/explore/tabs/passes-tab.tsx
- apps/website/components/templates/explore/types.ts
- apps/website/constants/queries.ts
- apps/website/locales/en/explore.json
- apps/website/services/hasura/queries/home.gql
> feat: pass section and tab on explore page

- apps/website/hooks/use-gate-status.tsx
> fix: fixed status to direct credential

- apps/website/components/templates/create-gate/tasks/direct/fields/direct-wallets-progress.tsx
- apps/website/components/templates/gate-view/draft-direct-holders-list/draft-direct-holders-list.tsx
- apps/website/components/templates/gate-view/gate-view-tasks.tsx
> hotfix: changed direct credential component to render a draft users

- apps/website/components/templates/create-gate/tasks/direct/fields/direct-wallets-progress.tsx
- apps/website/components/templates/gate-view/draft-direct-holders-list/draft-direct-holders-list.tsx
- apps/website/components/templates/gate-view/gate-view-tasks.tsx
- apps/website/hooks/use-gate-status.tsx
> Develop to Staging

- apps/website/components/templates/loyalty-program/loyalty-program/components/CredentialListItem.tsx
- apps/website/components/templates/loyalty-program/loyalty-program/components/CredentialsList.tsx
- apps/website/services/hasura/fragments/loyalty.gql
> fix: add a order to credentials

- apps/website/i18n.js
> fix: added locale to loyalty program page

- apps/website/components/templates/new-user/new-user.tsx
> fix: add a borderRight into signup box

- apps/website/components/templates/loyalty-program/loyalty-program/components/CredentialListItem.tsx
> fix: display ellipsis

- apps/website/components/molecules/options-credential.tsx
- apps/website/components/templates/gate-view/gate-view-sidebar.tsx
- apps/website/components/templates/gate-view/gate-view-tasks.tsx
- apps/website/components/templates/gate-view/gate-view.tsx
- apps/website/components/templates/gate-view/task-list.tsx
- apps/website/components/templates/loyalty-program/components/LoyaltySidebar.tsx
- apps/website/components/templates/loyalty-program/credential/components/LoyaltyProgramCredentialTasks.tsx
- apps/website/constants/queries.ts
- apps/website/hooks/use-loyalty-gates-completed.ts
- apps/website/pages/loyalty/credential/[id].tsx
- apps/website/services/hasura/queries/loyalty.gql
> feat: display admin controls

- apps/website/components/organisms/navbar/navbar-notifications/notifications/custom.tsx
- apps/website/components/organisms/navbar/navbar-notifications/notifications/custom/protocol-credential-notification.tsx
- apps/website/locales/en/notifications.json
- apps/website/services/hasura/queries/dao_profile.gql
Notifications for protocol credential
> feat: created protocol credential notification

- apps/website/components/templates/protocol/credentials/show/components/list-view.tsx
- [] - feature
- [] - chore
- [] - docs
> fix: adusted bullets view

- apps/website/components/templates/loyalty-program/LoyaltyProgram.tsx
- apps/website/components/templates/loyalty-program/LoyaltyProgramCredential.tsx
- apps/website/components/templates/loyalty-program/components/LoyaltySidebar.tsx
- apps/website/constants/queries.ts
- apps/website/pages/loyalty/[id].tsx
- apps/website/pages/loyalty/credential/[id].tsx
- apps/website/services/gateway-protocol/queries/credentials.gql
- apps/website/services/hasura/queries/gate.gql
- [] - bugfix
- [] - chore
- [] - docs
Lorem Ipsum
> feat: added see credential button

- apps/website/components/atoms/share-on.tsx
- apps/website/components/atoms/square-button.tsx
- apps/website/components/templates/loyalty-program/components/LoyaltySidebar.tsx
> feat: share loyalty program

- apps/website/hooks/use-loyalty-gates-completed.ts
- apps/website/services/hasura/queries/loyalty.gql
- [] - feature
- [] - chore
- [] - docs
Lorem Ipsum
> fix: remove whitelisted wallet query to list completed gates

- apps/website/components/templates/gate-view/gate-view-sidebar.tsx
- apps/website/components/templates/gate-view/gate-view.tsx
- apps/website/components/templates/gate-view/task-list.tsx
- apps/website/components/templates/loyalty-program/LoyaltyProgram.tsx
- apps/website/components/templates/loyalty-program/LoyaltyProgramCredential.tsx
- apps/website/components/templates/loyalty-program/components/LoyaltySidebar.tsx
- apps/website/constants/queries.ts
- apps/website/hooks/use-mint-data.tsx
- apps/website/pages/credential/[id].tsx
- apps/website/pages/loyalty/[id].tsx
- apps/website/pages/loyalty/credential/[id].tsx
- apps/website/services/hasura/queries/loyalty.gql
- [] - bugfix
- [] - chore
- [] - docs
> feat: added intermediate table to loyalty credentials

- apps/website/components/templates/create-gate/details-form.tsx
- [] - feature
- [] - chore
- [] - docs
> fix: change name to username

- apps/website/components/templates/gate-view/task-list.tsx
- apps/website/constants/queries.ts
- apps/website/hooks/use-mint-data.tsx
- apps/website/pages/credential/[id].tsx
- apps/website/pages/loyalty/[id].tsx
- apps/website/pages/loyalty/credential/[id].tsx
- apps/website/services/hasura/queries/gate.gql
- apps/website/services/hasura/queries/loyalty.gql
- [] - bugfix
- [] - chore
- [] - docs
Lorem Ipsum
> feat: created loyalty progress table

- apps/website/components/molecules/gate-mint-button.tsx
- apps/website/components/molecules/mint-dialog/mint-dialog.tsx
- apps/website/components/organisms/gates/view/modals/gate-completed.tsx
- apps/website/components/templates/gate-view/gate-view-sidebar.tsx
- apps/website/components/templates/gate-view/gate-view-tasks.tsx
- apps/website/components/templates/gate-view/gate-view.tsx
- apps/website/components/templates/loyalty-program/LoyaltyProgramCredential.tsx
- apps/website/components/templates/loyalty-program/components/LoyaltySidebar.tsx
- apps/website/components/templates/protocol/credentials/show/credential-show.tsx
- apps/website/hooks/use-mint-data.tsx
- apps/website/locales/en/credential.json
- [] - bugfix
- [] - chore
- [] - docs
> feat: optimizing mint button

- apps/website/components/organisms/gates/view/tasks/content/manual/components/comment-card.tsx
- apps/website/components/organisms/gates/view/tasks/content/manual/components/interation-list.tsx
- apps/website/components/organisms/gates/view/tasks/content/manual/components/submissions-detail-header.tsx
- apps/website/components/organisms/gates/view/tasks/content/manual/components/submissions-item.tsx
- apps/website/components/organisms/gates/view/tasks/content/manual/components/task-interation.tsx
- apps/website/components/organisms/gates/view/tasks/content/manual/manual.tsx
- apps/website/components/organisms/gates/view/tasks/content/manual/submission-detail.tsx
- apps/website/components/organisms/gates/view/tasks/content/manual/submissions.tsx
- apps/website/components/templates/gate-view/task-list.tsx
- [] - feature
- [] - chore
- [] - docs
Lorem Ipsum
> fix: added optional checkers

- apps/website/hooks/use-actual-tier.ts
- [] - feature
- [] - chore
- [] - docs
> fix: tier conditions

- src/components/features/daos/view/dao-profile.tsx
- [] - feature
- [] - chore
- [] - docs
> fix : displaying earn credential issue

- src/components/features/gates/create/tasks/direct/direct-wallets.tsx
- src/components/features/gates/create/tasks/direct/fields/direct-wallets-progress.tsx
> fix: fixed progress direct credentials uploading

- src/components/features/gates/create/create-gate.tsx
- src/components/features/gates/create/details-form.tsx
- src/components/features/gates/create/schema.ts
- src/components/molecules/form/creators-input.tsx
> fix: solved username problems during creating gate process

- .gitignore
- .vscode/settings.json
- pnpm-lock.yaml
- src/components/features/explore/tabs/daos-tab/daos-tab.tsx
- Call daos query using authenticated method
> feat: call daos query only authenticated

- locales/en/org-signup.json
- src/components/templates/org/signup/components/set-up-form-components.tsx
- src/components/templates/org/signup/components/step-form-header.tsx
- src/components/templates/org/signup/signup.tsx
> fix: fixed UI issues for org singup flow

- apps/website/components/templates/landing/investors/investors.tsx
> fix: fixed investors card -> Pre-main

- src/components/features/explore/tabs/daos-tab/daos-tab.tsx
- src/components/templates/dashboard/drawer/drawer.tsx
- src/components/templates/landing/landing.tsx
> fix: hidden org creation cards for unauthenticated users

- src/services/hasura/queries/me.gql
> fix: fixed following_daos queries

- i18n.js
- locales/en/org-signup.json
- src/components/atoms/text-with-paragraphs/text-with-paragraphs.tsx
- src/components/features/daos/view/dao-header.tsx
- src/components/features/daos/view/tabs/gates-tab/gates-tab.tsx
- src/components/templates/org/signup/components/step-success.tsx
- src/constants/socials.ts
- src/pages/dao/[slug]/index.tsx
- src/services/hasura/queries/dao-profile.gql
[Feature]
Waiting for approval page dialog and button.
**Tech Debt**
- I tried for days to implement a way to get the translation string text and append a React component to make the _email_ and _Discord_ links. To respect the deadline (in the sense that we aren't using translation on production) I added the text directly into the components.
> Feat/gtw 244/pending approval org page

- src/components/features/daos/view/tabs/overview-tab/overview-tab.tsx
- src/components/features/gates/create/create-gate.tsx
- src/components/features/gates/create/schema.ts
- src/components/organisms/publish-navbar/publish-navbar.tsx
- src/constants/queries.ts
- src/pages/credential/new.tsx
Display the publish button as disabled if the org is waiting for approval
> feat: display as disabled if the org is waiting for approval

- src/components/atoms/share-on.tsx
- src/components/features/loyalty/components/loyalty-sidebar.tsx
> fix: fixed error 500 trying to load loyalty page

- locales/en/gate-new.json
- src/components/atoms/alert.tsx
- src/components/features/gates/create/create-gate.tsx
- src/components/organisms/publish-navbar/publish-navbar.tsx
> feat: display alert on create gate if org is waiting for approval

- package.json
- tests/credential.issue.spec.ts
- [] - chore
Creating all the e2e for basic tests on credential issuing
> test credentials

- locales/en/dao-profile.json
- src/components/features/daos/view/dao-header.tsx
- src/constants/queries.ts
- src/services/hasura/mutations/daos.gql
> Feat/gtw 345/button approve org

- src/components/features/gates/view/gate-completed.tsx
- src/components/features/gates/view/gate-view-sidebar.tsx
- src/components/features/loyalty/components/loyalty-sidebar.tsx
- src/components/features/protocol/credentials/view/credential-view.tsx
- src/hooks/use-mint-data.tsx
> fix: removed unnecessary-query

- src/components/features/gates/view/gate-completed.tsx
- src/components/features/gates/view/gate-view-sidebar.tsx
- src/components/features/loyalty/components/loyalty-sidebar.tsx
- src/components/features/protocol/credentials/view/credential-view.tsx
- src/hooks/use-mint-data.tsx
> Revert "fix: removed unnecessary-query"

- locales/en/dashboard-new-user.json
- src/components/features/signup/forms/form-send-email.tsx
- src/components/features/signup/sections/signup-methods.tsx
- src/components/features/signup/signup.tsx
- src/components/features/signup/utlis/connect-more-auth-dialog.tsx
> feat: added button action to connect wallet

- src/components/features/signup/sections/signup-methods.tsx
> feat: added redirect after successful connection

- .gitignore
Ignore `.nvmrc` file from repository (set local NodeJS version)
> fix: ignore .nvmrc

- src/providers/auth/hooks.tsx
> fix: changed callback to redirect

- locales/en/settings.json
- src/components/features/settings/account-management/delete-id/delete-modal.tsx
Only strings and simple refactor
> update name and use the component

- src/components/features/profile/tabs/IssuedTab.tsx
- src/components/features/profile/tabs/ReceivedTab.tsx
- src/components/molecules/cards/credential-card.tsx
- src/components/organisms/data-grid/data-grid.tsx
- src/pages/model/[id]/credentials.tsx
- src/services/hasura/fragments/protocol/credentials.gql
- src/services/hasura/queries/protocol/credential.gql
- src/services/hasura/queries/protocol/data-models.gql
- src/services/hasura/queries/protocol/issuers.gql
- Fixed 500 errors when checking credential - improved querying on protocol side
- (Tentatively) improved data grid images (wip)
> Fix - get credential data

- src/components/organisms/navbar/navbar-avatar.tsx
> feat: update logged menu

- src/components/organisms/confirm-delete/confirm-delete.tsx
[Jira Ticket](https://mygateway.atlassian.net/browse/GTW-484?atlOrigin=eyJpIjoiYTA4OTRmZDMwMTY2NDdjZGIxYTJhMzM0M2FlZjA2YTUiLCJwIjoiaiJ9)
> fix: update confirm delete component validation

- locales/en/protocol.json
- src/components/features/protocol/data-models/view/components/overview-card-info.tsx
- src/components/features/protocol/data-models/view/components/overview-tab.tsx
- src/components/features/protocol/data-models/view/layout.tsx
- src/components/features/settings/account-management/email/components/list-emails.tsx
- src/components/organisms/data-grid/data-grid.tsx
- src/constants/queries.ts
- src/services/hasura/queries/protocol/data-models.gql
> feat: added consumption price field

- src/components/features/authentication/schema.ts
- src/components/features/settings/account-management/edit-id/edit-id.tsx
- src/components/features/settings/account-management/edit-id/schema.ts
- Display the right error message
- Fix the gateway ID regex
- [Jira ticket](https://mygateway.atlassian.net/browse/GTW-483?atlOrigin=eyJpIjoiYTYyMDRkM2RjZDIxNDc1OWExZmIyNTk5MTc1ZmI2M2EiLCJwIjoiaiJ9)
[GTW-483]: https://mygateway.atlassian.net/browse/GTW-483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: display error to update gatewayid choosing an existent gtwId

- src/services/hasura/queries/protocol/data-models.gql
> Develop -> Staging

- locales/en/authentication.json
> fix: fixed copy about e-mail

- src/components/features/settings/account-management/edit-id/edit-id.tsx
> fix: check other message

- src/components/features/protocol/data-models/view/components/overview-card-info.tsx
- src/services/hasura/queries/protocol/data-models.gql
- [] - feature
Shows datamodels created via Organization with a proper information
> Added conditional badge for verified datamodels

- locales/en/settings.json
- src/components/features/settings/account-management/delete-id/delete-modal.tsx
> feat: add a snackbar on delete account success

- src/components/atoms/share-on.tsx
- src/services/hasura/queries/credential.gql
- src/services/hasura/queries/loyalty.gql
- src/services/hasura/queries/protocol/credential.gql
- src/utils/credential/build-image-url-params.ts
> fix: fixed data into sharing modal

- i18n.js
- locales/en/quest.json
- src/components/features/daos/view/tabs/overview-tab/quest/components/ClaimFormQuest.tsx
- src/components/features/daos/view/tabs/overview-tab/quest/components/credential-template.tsx
- src/components/features/daos/view/tabs/overview-tab/quest/components/details-template.tsx
- src/components/features/daos/view/tabs/overview-tab/quest/components/optional-settings-template.tsx
- src/components/features/daos/view/tabs/overview-tab/quest/components/tasks-template.tsx
- src/components/features/daos/view/tabs/overview-tab/quest/components/vertical-setpper.tsx
- src/components/features/daos/view/tabs/overview-tab/quest/create-quest.tsx
- src/components/features/daos/view/tabs/overview-tab/quest/dialog-structure.tsx
- responsiveness
- locals
- styles
- flows
> style : fix

- locales/en/settings.json
- src/components/features/settings/developer/components/usage-limit-item.tsx
- src/components/features/settings/developer/components/usage-limit.tsx
- src/constants/queries.ts
- src/services/hasura/queries/protocol/api.gql
> feat: integrated components with the api to get usage limit

- src/components/features/authentication/components/authentication-options.tsx
> fix: design tweaks

- src/components/features/settings/developer/components/usage-limit.tsx
> Revert "update staging"

- src/components/features/authentication/components/authentication-options.tsx
> fix: caption variant

- src/components/features/protocol/components/authenticated-by.tsx
- src/components/features/protocol/components/card-users.tsx
- src/components/features/protocol/components/credential-card-info.tsx
- src/components/features/protocol/credentials/view/components/revoke-credential.tsx
- src/components/features/protocol/credentials/view/credential-view.tsx
- src/hooks/use-mint-data.tsx
- src/services/hasura/queries/protocol/credential.gql
- show revoke button if logged in user is issuer
- fix some data on the user card
> Fix: Revoke Button & User Card Data

- src/components/features/protocol/data-models/view/components/overview-card-info.tsx
- src/services/hasura/queries/protocol/data-models.gql
- fixed organization image on data model page
> Fix: organization image on data model page

- locales/en/common.json
- locales/en/gate-profile.json
- src/components/atoms/icons/task-icon.tsx
- src/components/features/gates/create/tasks/twitter-tweet/twitter-tweet.tsx
- src/components/features/gates/view/gate-view-sidebar.tsx
- src/components/features/gates/view/tasks/github/github_contribute.tsx
- src/components/features/gates/view/tasks/github/github_prs.tsx
- src/components/features/gates/view/tasks/manual/manual.tsx
- src/components/features/gates/view/tasks/meeting_code.tsx
- src/components/features/gates/view/tasks/nft_hold.tsx
- src/components/features/gates/view/tasks/quiz.tsx
- src/components/features/gates/view/tasks/recaptcha.tsx
- src/components/features/gates/view/tasks/self-verify.tsx
- src/components/features/gates/view/tasks/snapshot.tsx
- src/components/features/gates/view/tasks/task-list.tsx
- src/components/features/gates/view/tasks/task.tsx
- src/components/features/gates/view/tasks/token_hold.tsx
- src/components/features/gates/view/tasks/track_onchain.tsx
- src/components/features/gates/view/tasks/twitter/twitter_follow.tsx
- src/components/features/gates/view/tasks/twitter/twitter_like.tsx
- src/components/features/gates/view/tasks/twitter/twitter_retweet.tsx
- src/components/features/gates/view/tasks/twitter/twitter_tweet.tsx
- src/components/molecules/form/emoji-picker/emoji-picker.tsx
- src/hooks/use-countdown.tsx
> feat: created front-end components to validate on chain events

- src/components/features/settings/account-management/wallet/hooks.tsx
Improve error message on add wallet modal
> fix: error message on add wallet

- src/components/features/gates/create/tasks/track-onchain/__mock__.ts
> fix: fixed variable

- src/components/features/gates/view/tasks/track_onchain.tsx
> feat: added variables

- src/components/features/gates/create/schema.ts
- src/components/features/gates/create/tasks/track-onchain/components/parameters.tsx
- src/components/features/gates/create/tasks/track-onchain/track-onchain-events.tsx
> fix: added type to parameters

- src/components/features/gates/create/tasks/track-onchain/components/parameters.tsx
- src/components/features/gates/create/tasks/track-onchain/track-onchain-events.tsx
> fix: bytes type and parameters creation

- src/components/features/settings/account-management/email/email-alias.tsx
- src/components/features/settings/account-management/migration/migration-modal.tsx
- fix migration modal title
- fix qa description
> fix: correct qa description username

- src/components/organisms/data-grid/data-grid.tsx
> fix: fixed params

- src/components/features/gates/view/tasks/track_onchain.tsx
- src/utils/web3.ts
> fix: added chain name

- src/components/features/gates/create/tasks/track-onchain/track-onchain-events.tsx
> fix: reset ABI state after change the chain

- .vscode/launch.json
- src/components/organisms/confirm-delete/confirm-delete.tsx
> Feat/gtw 637/email migration did not work

- src/components/features/gates/create/schema.ts
> fix: fixed schema

- src/components/features/gates/create/schema.ts
- src/components/features/gates/create/tasks/track-onchain/track-onchain-events.tsx
- src/constants/error-messages.ts
> Dev -> Staging

- locales/en/gate-new.json
- src/components/features/gates/create/tasks/track-onchain/track-onchain-events.tsx
[Flow](https://s3.amazonaws.com/img0.recordit.co/2DepVUj189.mp4?AWSAccessKeyId=AKIAUQ5RURZ7ND2T2B6I&Expires=1691021812&Signature=gwj9aPlnWqMEZZeolL8i5K3WEGA=)![image](http://g.recordit.co/ixMeckzebN.gif)
> fix: validate if ABI has event to display the Event select

- src/components/features/gates/create/tasks/track-onchain/track-onchain-events.tsx
[GTW-660]: https://mygateway.atlassian.net/browse/GTW-660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: display event flow

- src/components/features/profile/tabs/IssuedTab.tsx
- src/components/features/profile/tabs/ReceivedTab.tsx
[Jira ticket](https://mygateway.atlassian.net/browse/GTW-662?atlOrigin=eyJpIjoiY2FkMjNhMDA0OGQ4NDYxN2JhZTk4MTRiOTc3MDlmMDIiLCJwIjoiaiJ9)
> Fix the pagination problem on profile page for loading credentials

- src/components/molecules/cards/data-model-card.tsx
- src/services/hasura/queries/protocol/data-models.gql
Same PR but the styles are changed and previously the image was not there in gql file so changed that as well.
[Set default image for data models](https://mygateway.atlassian.net/browse/GTW-661?atlOrigin=eyJpIjoiY2MxOGJlNmJhMzQ5NGJjOGEwNzk3MDk5NDlhYjExYWMiLCJwIjoiaiJ9)
> Set default image for data models

- src/components/features/gates/create/tasks/add-task-button.tsx
- src/components/features/gates/create/tasks/add-task-card.tsx
- temporarily disable Twitter tasks
> feat: disable twitter tasks

- locales/en/index.json
- [] - feature
- [] - bugfix
- [] - chore
- [] - docs
Lorem Ipsum
> fix: landing page texts

- src/components/features/loyalty/components/credential-list-item.tsx
- src/components/features/loyalty/components/credentials-list.tsx
- src/services/hasura/queries/credential.gql
> Add points to credentials

- src/components/features/loyalty/components/tier.tsx
- src/components/templates/og-image/og-image-loyalty-pass.tsx
- src/pages/api/og-image/loyalty-pass.tsx
- src/services/hasura/fragments/loyalty.gql
- src/utils/loyalty-pass/build-image-url-params.ts
- src/utils/loyalty-pass/colors.ts
##Feature
[Jira ticket](https://mygateway.atlassian.net/browse/GTW-663?atlOrigin=eyJpIjoiNTI0OGZhMzE3YzI2NDQ1ZDhjYWVjOGQ4OGM4MGRkYjMiLCJwIjoiaiJ9)
> styles:fixed og image styles

- locales/en/loyalty-program.json
- src/components/features/loyalty/components/credential-list-item.tsx
- src/components/features/loyalty/components/credentials-list.tsx
- src/components/features/loyalty/components/loyalty-sidebar.tsx
- src/components/features/loyalty/loyalty-credential.tsx
- src/hooks/use-mint-data.tsx
- src/services/hasura/queries/credential.gql
> feat: create dynamic loyalty image

- src/components/features/loyalty/components/tier.tsx
- src/components/features/loyalty/loyalty.tsx
- src/components/molecules/cards/loyalty-program-card.tsx
- src/services/hasura/queries/loyalty.gql
- Link loyalty progress to credential claim
> Fix: link loyalty progress to credential claim

- src/components/features/explore/tabs/all-tab/banner/banner.tsx
- Added URL on LiFi banner
- Added new env file
> fix: add URL on banner

- src/components/atoms/share-on.tsx
- src/components/features/loyalty/components/tier.tsx
- src/components/features/loyalty/loyalty.tsx
> Pre-main -> main

- src/components/features/loyalty/components/tier.tsx
- src/components/features/loyalty/loyalty.tsx
- src/components/molecules/modal/modal-share-credential.tsx
- src/pages/api/og-image/loyalty-pass.tsx
- src/services/hasura/queries/loyalty.gql
> fix: og image not working

- locales/en/protocol.json
- src/components/features/protocol/credentials/create/components/issue-by-form.tsx
- src/components/features/protocol/credentials/create/credential-create.tsx
- Trim recipientUserIdentity value from form
- Added first org as default
- Changed copy to include emails
> Pre main -> main

- src/components/features/gates/view/gate-completed.tsx
- [] - feature
- [] - chore
- [] - docs
Missing space between PDA and for
> Fix Success Message on Gate Completed

- src/components/features/daos/view/tabs/overview-tab/base/general-form.tsx
- src/components/features/gates/create/tasks/direct/direct-wallets-lists.tsx
- src/components/features/gates/create/tasks/direct/direct-wallets.tsx
- src/components/features/gates/view/tasks/direct-holders-list/direct-holders-list.tsx
- src/services/hasura/mutations/gate.gql
- src/services/hasura/queries/credential.gql
- src/services/hasura/queries/loyalty.gql
Same as pr title
[Jira ticket](https://mygateway.atlassian.net/browse/GTW-604?atlOrigin=eyJpIjoiOTA5MjJiM2U5YjE4NGRkMjhmYjQ4OGRjODI1ZjNiYmEiLCJwIjoiaiJ9)
> Allow user to delete recipient after csv upload

- src/pages/_app.tsx
Just remove hotjar from Odyssey
> fix: remove hotjar

- src/components/features/explore/tabs/all-tab/all-tab.tsx
- src/components/features/explore/tabs/all-tab/banner/banner.tsx
- src/components/features/explore/tabs/all-tab/banner/card-credit-score.tsx
- src/components/features/explore/tabs/all-tab/banner/card-earn-credential.tsx
- src/components/features/protocol/components/authenticated-by.tsx
- src/components/features/protocol/components/card-users.tsx
- src/components/features/protocol/credentials/create/components/claim-form-text.tsx
- src/components/features/protocol/credentials/create/components/credential-create-container.tsx
- src/components/features/protocol/credentials/create/components/general-info-form.tsx
- src/components/features/protocol/credentials/create/components/image-field.tsx
- src/components/features/protocol/credentials/create/components/recipient-form.tsx
- src/components/features/protocol/credentials/create/components/successfully-created.tsx
- src/components/features/protocol/credentials/view/components/activities.tsx
- src/components/features/protocol/credentials/view/credential-view.tsx
- src/components/features/protocol/data-models/view/components/issue-credential-button.tsx
- src/pages/_app.tsx
> feat:removed tag manager and hotjar scripts
